# Generated by Django 4.2.3 on 2023-07-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(upload_to='product')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='product')),
                ('dimension', models.FloatField()),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('delivery', models.FloatField(blank=True, null=True)),
                ('stock', models.FloatField()),
                ('unit', models.IntegerField()),
                ('category', models.IntegerField()),
                ('colors', models.TextField(blank=True, null=True)),
                ('sizes', models.TextField(blank=True, null=True)),
                ('tastes', models.TextField(blank=True, null=True)),
                ('smells', models.TextField(blank=True, null=True)),
                ('textures', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sales', models.IntegerField(default=0)),
            ],
        ),
    ]
