# Generated by Django 3.0.8 on 2023-06-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20230531_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='web',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messenger',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
