# Generated by Django 3.0.8 on 2023-01-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='averageReview',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shop',
            name='averageTime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shop',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
