# Generated by Django 3.0.8 on 2023-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230128_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
