# Generated by Django 3.0.8 on 2023-01-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230128_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='averageReview',
        ),
    ]
