# Generated by Django 3.0.8 on 2023-01-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantityCUP', models.FloatField()),
                ('quantityMLC', models.FloatField()),
            ],
        ),
    ]
