# Generated by Django 4.2.3 on 2023-07-04 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
