# Generated by Django 3.0.8 on 2023-01-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_petition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
